--SQL SERVER
--CRIAR NOVO BANCO DE DADOS

USER MASTER
GO

--FORMA SIMPLES
CREATE DATABASE BD_LOJA_CONSTRUCAO_SQL;

-- APAGAR O BANCO DE DADOS
DROP DATABASE BD_LOJA_CONSTRUCAO_SQL

-- FORMA COMPLETA (configurações avançadas)
CREATE DATABASE BD_LOJA_CONSTRUCAO_SQL
ON
(NAME = BD_LOJA_CONSTRUCAO_SQL,
        FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\BD_LOJA_CONSTRUCAO_SQL.MDF',
		SIZE=100MB,
		MAXSIZE= 1GB,
		FILEGROWTH=50MB)
LOG ON
(NAME = BD_LOJA_CONSTRUCAO_SQL_LOG,
        FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\BD_LOJA_CONSTRUCAO_SQL.LDF',
		SIZE=10MB,
		MAXSIZE=100MB,
		FILEGROWTH=10MB);
GO
